# Manastr CDK Cashu Mint Configuration
# Full-featured mint with fake Lightning backend for testing

[info]
url = "http://127.0.0.1:3334/"
listen_host = "127.0.0.1"
listen_port = 3334
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
# Small input fee for testing
input_fee_ppk = 0
enable_swagger_ui = true

[mint_management_rpc]
enabled = false

[info.http_cache]
# Use in-memory cache for testing
backend = "memory"
ttl = 60
tti = 60

[mint_info]
name = "Manastr Gaming Mint"
description = "Full CDK Cashu mint for Manastr gaming with dual currency support"
description_long = "Revolutionary gaming mint using Cashu for decentralized strategy game tokens. Supports mana (gameplay currency) and loot (reward currency) with cryptographically-secure army generation from token C values."
motd = "🎮 Gaming mint operational! Use mana tokens for army generation via C values."
contact_email = "mint@manastr.game"

[database]
# Use SQLite database for persistence
engine = "sqlite"

[ln]
# Use fake wallet for testing - automatically fills payment quotes
ln_backend = "fakewallet"
min_mint = 1
max_mint = 1000000
min_melt = 1
max_melt = 1000000

[fake_wallet]
# Fake Lightning backend configuration for testing
supported_units = ["sat"]
fee_percent = 0.01  # 1% fee for testing
reserve_fee_min = 1  # Minimum 1 sat reserve
min_delay_time = 1   # 1 second minimum delay
max_delay_time = 2   # 2 second maximum delay