[server]
host = "127.0.0.1"
port = 4444

[nostr]
relay_url = "ws://localhost:7777"
private_key = "game_engine_bot_private_key_hex"

[cashu]
mint_url = "http://localhost:3333"

[game]
max_concurrent_matches = 100
round_timeout_seconds = 300
match_timeout_seconds = 1800
loot_reward_per_match = 1000
